[project]
name = "threshold-guardian"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.threshold-member]
path = "contracts/threshold-member.clar"
depends_on = []

[contracts.guardian-leaderboard]
path = "contracts/guardian-leaderboard.clar"
depends_on = []

[contracts.guardian-rewards]
path = "contracts/guardian-rewards.clar"
depends_on = []

[contracts.guardian-registry]
path = "contracts/guardian-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
